version: '3.9'

services:
  concourse-db:
    image: postgres
    platform: linux/arm64
    environment:
      POSTGRES_DB: &PG_DBNAME concourse
      POSTGRES_PASSWORD: &PG_PASSWORD concourse_pass
      POSTGRES_USER: &PG_USER concourse_user
      PGDATA: /database

  concourse:
    image: rdclda/concourse:7.9.1
    platform: linux/arm64
    command: quickstart
    privileged: true
    depends_on:
      - concourse-db
    ports:
      - "8080:8080"
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: *PG_USER
      CONCOURSE_POSTGRES_PASSWORD: *PG_PASSWORD
      CONCOURSE_POSTGRES_DATABASE: *PG_DBNAME
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_WORKER_SWEEP_INTERVAL: 24h
      # If running on a non M1/M2 MacOS, optionally change this to overlay
      # CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: naive
      CONCOURSE_WORKER_BAGGAGECLAIM_DISABLE_USER_NAMESPACES: true
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
      CONCOURSE_X_FRAME_OPTIONS: allow
      CONCOURSE_CONTENT_SECURITY_POLICY: "*"
      CONCOURSE_CLUSTER_NAME: tutorial
      CONCOURSE_WORKER_WORK_DIR: /worker-state
      # If running on a non M1/M2 MacOS, optionally change this to guardian (default) or containerd (if cgroupsv2 is supported by the host)
      # CONCOURSE_WORKER_RUNTIME: "houdini"
      CONCOURSE_WORKER_RUNTIME: "houdini"
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
