# Test configuration with smaller repositories for testing
repositories:
  - owner: semver
    repo: semver
    description: "Semantic versioning specification"
  
  - owner: github
    repo: gitignore
    description: "Collection of gitignore templates"
  
  - owner: kelseyhightower
    repo: envconfig
    description: "Simple environment configuration for Go"

settings:
  rate_limit_delay: 1.0
  max_releases_per_repo: 5
  include_prereleases: false