---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: python
    tag: "3.11-slim"

inputs:
  - name: downloads
    path: /downloads
  - name: release-monitor-repo
    path: /app

params:
  ARTIFACTORY_URL: ((artifactory_url))
  ARTIFACTORY_REPOSITORY: ((artifactory_repository))
  ARTIFACTORY_API_KEY: ((artifactory_api_key))
  ARTIFACTORY_SKIP_SSL_VERIFICATION: ((artifactory_skip_ssl_verification))

run:
  path: /bin/bash
  args:
    - -exc
    - |
      set -e
      # Navigate to repo directory
      cd /app
      # Install required dependencies
      ./ci/tasks/upload-to-artifactory/task.sh