---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: python
    tag: "3.11-slim"

inputs:
  - name: downloads
    path: /downloads
  - name: release-monitor-repo
    path: /app

params:
  ARTIFACTORY_URL:
  ARTIFACTORY_REPOSITORY:
  ARTIFACTORY_API_KEY:
  ARTIFACTORY_USERNAME:
  ARTIFACTORY_PASSWORD:
  ARTIFACTORY_SKIP_SSL_VERIFICATION:
  CONFIG_PATH: config.yaml  # Configuration file path for target version settings

run:
  path: /bin/bash
  args:
    - -exc
    - |
      set -e
      # Navigate to repo directory
      cd /app
      # Install required dependencies
      ./ci/tasks/upload-to-artifactory/task.sh
