---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: python
    tag: "3.11-slim"

inputs:
  - name: release-monitor-repo
  - name: release-output

outputs:
  - name: email

params:
  # Email configuration
  EMAIL_SUBJECT_PREFIX: "[GitHub Release Monitor]"
  INCLUDE_ASSET_DETAILS: true
  REPOSITORIES_OVERRIDE: ""

  # Path configuration (defaults work for Concourse structure)
  RELEASES_INPUT_DIR: "../release-output"
  EMAIL_OUTPUT_DIR: "../email"

  # Version database configuration for filtering
  USE_S3_VERSION_DB: false
  DISABLE_S3_VERSION_DB: false
  VERSION_DB_S3_BUCKET: ""
  VERSION_DB_S3_PREFIX: "version-db/"
  S3_USE_MC: false

  # S3 credentials (will be passed from pipeline)
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  S3_ENDPOINT: ""
  S3_SKIP_SSL_VERIFICATION: false

run:
  path: /bin/bash
  args:
    - -exc
    - |
      # Navigate to repo directory
      cd release-monitor-repo

      # Export S3 endpoint for boto3 to use
      if [[ -n "$S3_ENDPOINT" ]]; then
        export AWS_ENDPOINT_URL="$S3_ENDPOINT"
        export AWS_ENDPOINT_URL_S3="$S3_ENDPOINT"
        echo "Using S3 endpoint: $S3_ENDPOINT"
      fi

      # Install required dependencies
      pip3 install --quiet pyyaml jinja2 boto3

      # Run the email generation script
      python3 ci/tasks/send-release-notification/generate_email.py
