---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: python
    tag: "3.11-slim"

inputs:
  - name: release-monitor-repo
    path: /app
  - name: version-db
    path: /tmp/version-db
    optional: true

outputs:
  - name: release-output
    path: /release-output
  - name: release-state
    path: /tmp/release-state

params:
  CONFIG_FILE: config.yaml
  CONTINUE_ON_API_ERROR: "false"
  GITHUB_TOKEN: ((github_token))
  GITHUB_SKIP_SSL_VERIFICATION: "false"
  HTTP_PROXY: ""
  HTTPS_PROXY: ""
  NO_PROXY: ""
  LOG_LEVEL: info
  REPOSITORIES_OVERRIDE: "{}"
  REPOSITORY_OVERRIDES: "{}"
  S3_USE_MC: "false"
  STATE_FILE: /tmp/release-state/release_state.json

run:
  path: /bin/bash
  args:
    - -exc
    - |
      set -e
      # Navigate to repo directory
      cd /app
      # Install required dependencies
      apt-get update && apt-get install -y curl
      ./ci/tasks/check-releases/task.sh
