---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: python
    tag: "3.11-slim"

inputs:
  - name: release-monitor-repo
    path: /app
  - name: version-db
    path: /tmp/version-db
    optional: true

outputs:
  - name: release-output
    path: /release-output
  - name: release-state
    path: /tmp/release-state

params:
  GITHUB_TOKEN: ((github_token))
  CONFIG_FILE: config.yaml
  STATE_FILE: /tmp/release-state/release_state.json

run:
  path: /bin/bash
  args:
    - -exc
    - |
      set -e
      # Navigate to repo directory
      cd /app
      # Install required dependencies
      apt-get update && apt-get install -y curl
      ./ci/tasks/check-releases/task.sh
