# Concourse Task: Download GitHub Releases
# Downloads GitHub release assets based on monitor output

platform: linux

image_resource:
  type: registry-image
  source:
    repository: python
    tag: 3.11-slim

inputs:
  - name: release-monitor
    path: /opt/release-monitor
  - name: monitor-output
    path: /tmp/monitor-output

outputs:
  - name: downloads
    path: /tmp/downloads
  - name: version-db
    path: /tmp/version-db

params:
  # Required parameters
  GITHUB_TOKEN: ((github_token))

  # Download configuration
  DOWNLOAD_DIR: /tmp/downloads
  VERSION_DB_PATH: /tmp/version-db/version_db.json

  # S3 version database configuration (optional)
  USE_S3_VERSION_DB: false
  VERSION_DB_S3_BUCKET: ""
  VERSION_DB_S3_PREFIX: ""
  VERSION_DB_S3_REGION: ""

  # AWS credentials (required if USE_S3_VERSION_DB is true)
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""

  # S3 endpoint configuration for S3-compatible storage
  S3_ENDPOINT: ""
  S3_SKIP_SSL_VERIFICATION: false

  # Optional parameters
  CONFIG_FILE: config.yaml
  VERBOSE: false
  DRY_RUN: false

  # Asset filtering patterns (JSON array)
  ASSET_PATTERNS: '["*.tar.gz", "*.zip", "!*-sources.zip"]'

  # Download settings
  INCLUDE_PRERELEASES: "false"
  VERIFY_DOWNLOADS: "true"
  CLEANUP_OLD_VERSIONS: "true"
  KEEP_VERSIONS: "5"
  DOWNLOAD_TIMEOUT: "300"

  # Repository overrides (JSON object)
  REPOSITORY_OVERRIDES: "{}"

run:
  path: /opt/release-monitor/ci/tasks/download-releases/task.sh
