# Concourse Pipeline for GitHub Release Monitoring
# This pipeline runs the release monitoring script on a schedule

resources:
  - name: release-monitoring-repo
    type: git
    source:
      uri: ((git_repo_uri))
      branch: ((git_branch))
      private_key: ((git_private_key))

  - name: schedule-trigger
    type: time
    source:
      interval: 1h  # Check every hour

  - name: s3-output
    type: s3
    source:
      bucket: ((s3_bucket))
      region_name: ((s3_region))
      access_key_id: ((s3_access_key))
      secret_access_key: ((s3_secret_key))
      versioned_file: release-monitoring/latest-releases.json

jobs:
  - name: monitor-releases
    plan:
      - in_parallel:
          - get: release-monitoring-repo
          - get: schedule-trigger
            trigger: true

      - task: check-releases
        file: release-monitoring-repo/ci/tasks/check-releases/task.yml

      - put: s3-output
        params:
          file: release-output/releases.json
          content_type: application/json

  - name: process-new-releases
    plan:
      - in_parallel:
          - get: release-monitoring-repo
          - get: s3-output
            trigger: true
            passed: [monitor-releases]

      - task: download-and-store-tarballs
        file: release-monitoring-repo/ci/tasks/download-tarballs/task.yml

# Resource types (if not available in your Concourse deployment)
resource_types:
  - name: s3
    type: docker-image
    source:
      repository: concourse/s3-resource